# Generated by Django 2.0 on 2017-12-21 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField()),
                ('message', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Mediocre'), (4, 'Good'), (5, 'Awesome')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brief_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Country')),
                ('features', models.ManyToManyField(blank=True, to='hotels.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frees_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('daily_ratio', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Hotel'),
        ),
    ]
